services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: python bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
