version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"  # expose Flask API
    volumes:
      - .:/app
    working_dir: /app
    command: python bot.py
