services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    working_dir: /app
    command: python bot.py
    network_mode: host